# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

# Book settings
title: Hands-on Network Machine Learning with Scikit-Learn and Graspologic
logo: logo.png
author: Alexander Russell Loftus
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
repository:
  url: https://github.com/loftusa/thesis
  path_to_book: network_machine_learning_in_python
  
# sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_show_sphinx: false
  extra_extensions:
    # - jupyterbook_latex
bibtex_bibfiles:
  - references.bib
# HTML-specific settings
html:
  navbar_number_sections: true

# latex settings
latex:
  latex_engine: pdflatex